# Generated by Django 4.2.5 on 2023-09-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='Unknown', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(default='Ram', max_length=20),
            preserve_default=False,
        ),
    ]
